authors:
  luca:
    name: Luca Berton
    description: 18+ years in AI, cloud, and automation, leads innovative projects and educates 15,000+ students online.
    avatar: https://avatars.githubusercontent.com/lucab85
    url: https://www.lucaberton.com